import { ChapterInfo } from './types';

export const CHAPTERS: ChapterInfo[] = [
  {
    number: 0,
    title: 'The Prior Problem',
    summary: 'Why the mental model you bring to golf actively works against you — and what to do about it.',
    keyConcepts: [
      'A prior is the brain\'s predictive model built from past experience. Your golf prior was built from learning environments where "practice feels like improvement" — which is wrong in golf.',
      'The 0.0005-Second Feedback Problem: the ball only reports what happened at impact, in a window the conscious mind cannot control, making ball flight a corrupted learning signal during construction.',
      'Golf is unique: a complete beginner can produce the same outcome as the best player in the world on a single shot. This makes luck indistinguishable from skill, which causes the brain to learn the wrong lesson.',
      'The Inverse Relationship: there is likely an inverse relationship between your most technically correct swing and your best ball-striking. Deliberate monitoring disrupts fluid motor execution.',
      'The lesson tee was architecturally optimized for the lesson hour — not for long-term transfer. "The shot that worked before you left" is a seductive but misleading success metric.',
      'The Scroll: social media instruction teaches you to need more instruction. New competing cues arriving faster than any single one can be encoded prevents pattern consolidation.',
      'The ego doesn\'t resist change by announcing itself — it post-rationalizes in real time, constructing a story about why what just happened was fine.',
      'Metacognition — the ability to think about your own thinking — is not a personality trait. It is a trainable skill.',
    ],
  },
  {
    number: 1,
    title: 'The Foam Pit',
    summary: 'The neurological case for removing the ball from practice — and why it changes everything.',
    keyConcepts: [
      'Dual-Task Law: the effective working memory capacity for encoding a novel motor pattern while managing ball flight is 1–2 functional chunks — not the 7 of Miller\'s Law.',
      'The Bucket: the golfer\'s internal cognitive load. The Slope: external consequence (outcome pressure). Together they define the Map.',
      'The Construction Penalty: when a golfer\'s best technical swings produce their worst shots, the brain reverts to the old pattern.',
      'Reducing swing thoughts from six to one still fails because the Slope (the ball) is still present.',
      'The Fosbury Flop: removing a constraint reveals that what was always optimal finally becomes possible.',
      'The 2 AM garage session proved that constructing without a ball — removing the slope entirely — allows deeply ingrained patterns to change that resisted change for decades with a ball present.',
      'The first shank when returning to a real ball is a calibration problem, not evidence the work failed.',
      'Parallax collapsed the feedback loop from 78 trips to a tripod to approximately two seconds.',
      'Attempting to simultaneously build a new motor pattern and hit an acceptable shot is neurologically impossible due to Dual-Task Interference.',
    ],
  },
  {
    number: 2,
    title: 'The Map',
    summary: 'A two-axis framework for understanding where you are practicing and whether it\'s working.',
    keyConcepts: [
      'The Map\'s Y-axis: Guidance (Bucket fullness / internal cognitive load). X-axis: Consequence (external outcome pressure).',
      'The Golden Rule: when internal load goes up, external consequence must go down; when consequence goes up, load must be dumped.',
      'The Messy Middle: moderate bucket + moderate slope — the most comfortable address that produces the least durable transfer.',
      'Illusionist Trap: a golfer who believes they are inhabiting a zone they are not actually in.',
      'The Firewall: the checkpoint at every zone boundary where the golfer declares zone, persona, and permitted tools.',
      'The Skill Band: the diagonal range of Bucket/Slope combinations a golfer can navigate without pattern breakdown — wide for experts, narrow for beginners.',
      'Tennis balls compress into marbles through thousands of correct reps on flat ground, myelinating the neural pathway.',
      'A Drifter slides out of a zone without consciously deciding to. A Prisoner cannot leave a zone even when they want to.',
      'The upper-right quadrant: maximum internal load + maximum external consequence = Dual-Task Law violation in its purest form.',
      'The optimal trajectory: from upper-left (max guidance, zero consequence) toward lower-right (zero guidance, max consequence).',
    ],
  },
  {
    number: 3,
    title: 'Decoding Your Practice DNA',
    summary: 'Understanding the forces that shaped how you practice — and how to override the bad ones.',
    keyConcepts: [
      'The three forces shaping Practice DNA: Personality, Instruction History, and Culture/Constraints.',
      'Seve Ballesteros\'s decline: he tried to replace the Artist with the Engineer — filling the bucket that had always been empty, destroying the self-organizing system.',
      'The Forging Season: the off-season period of maximum Assembly Line emphasis when competitive pressure is absent.',
      'High Neuroticism: most likely to avoid the Warrior zone because pressure floods the attentional system.',
      'Ghost of the Infinite Scroll: new technique every Tuesday means the brain never performs the deep repetition required to encode anything permanently.',
      'Drew\'s story: the Illusionist failure mode — sessions looked productive but were permanently in the Messy Middle.',
      'Cultural constraints (e.g., 5-month golf season) become default practice habits even when the constraint is removed.',
      'Tiger vs. Seve: you can change everything about a swing while preserving the Artist\'s attentional architecture. The Arena identity survives the storm, not the swing positions.',
      'The False Engineer is the most dangerous Illusionist trap — feeling like building while actually surviving on ball flight feedback.',
      'The Fourth Dimension of Practice DNA: Time — most golfers build when they should trust and trust when they should build.',
    ],
  },
  {
    number: 4,
    title: "The Scientist's Philosophy",
    summary: 'Why the nervous system is the best teacher — when you give it accurate inputs.',
    keyConcepts: [
      'Randy\'s three-year shank problem was a calibration problem (broken internal contact map), not a swing problem.',
      'The Sabertooth Machinery requires: a clear external task, accurate feedback, and freedom to adjust.',
      'The Car Crash Problem: impact happens in 0.0005 seconds — path, face angle, and contact point blur into a single corrupt signal.',
      'The A.C.E. Loop: Analyze, Calibrate, Exaggerate.',
      'The 49-Golfer Study: the strongest statistical relationship was between handicap and horizontal impact location error.',
      'Calibrate before building — if perceptual instruments aren\'t calibrated, you\'ll automate the wrong pattern.',
      '"Calibration problems wearing construction costumes": problems that are fundamentally about corrupt perception but get treated as construction problems.',
      'The Slicer\'s Trap: positive reinforcement (clean contact from swinging left) deepens a mechanically flawed attractor until it becomes identity.',
      'The Assembly Line is slow because construction requires overwriting a deeply grooved attractor state.',
      'Randy\'s solution — miss the ball on purpose — restored the Sabertooth Machinery\'s self-organizing system.',
    ],
  },
  {
    number: 5,
    title: "The Scientist's Diagnostics",
    summary: 'A systematic framework for reading what the ball is actually telling you.',
    keyConcepts: [
      'Triage Sequence: Path → Contact → Face (in that order). Face cannot be diagnosed until path and contact are stable.',
      'Hit-Guess-Look Protocol: the gap between the guess and reality is the Perception-Action Gap.',
      'Contact calibration standard: guess correctly within half an inch of actual contact on 8 out of 10 shots.',
      'Monte Carlo simulation: a 5% biased 15-handicapper loses 3.5 to 4.5 strokes per round before accounting for the cognitive tax.',
      'The Guidance Hypothesis (Salmoni, Schmidt & Walter): augmented feedback produces faster acquisition but worse retention when removed.',
      'Face bias is diagnosed by reading the dispersion pattern of center-struck shots only.',
      'The "invisible tax" of directional bias: an automatic compensatory adjustment costing attentional resources before the backswing even begins.',
      'The Lab exists because of "0.0005 seconds" — impact happens too fast for the nervous system to self-calibrate through feel alone.',
      'Joe\'s high backspin problem: a subtly open face drove him toward an early release, preventing the shaft lean that would have reduced spin.',
      'Late low point warning: some golfers get a late low point because they\'re coming over the top to compensate — requiring Assembly Line work, not more calibration.',
    ],
  },
  {
    number: 6,
    title: "The Scientist's Toolkit",
    summary: 'The specific tools — Impact Opposites, constraints, external cues — and when to use each.',
    keyConcepts: [
      'The Radio Dial: Lab calibrates from 95.3 to 101.5 in hours; Assembly Line closes the last fraction from 101.5 to 101.7 in weeks.',
      'Differential Learning (Schöllhorn): the nervous system maps faster from edges than from increments.',
      'The Zone Rule: go from Point A to Point C, then back to Point B — not the same bad shots.',
      'The Learning Ladder: Constraint + Tee → Tee only → Clean lie on grass.',
      'Opposite Miss Challenge score of 0/10: the bias is too deep for Lab calibration — Assembly Line is the required next step.',
      'External cues: direct attention toward the effect of movement on the environment, not toward body parts.',
      'Remove a constraint when the golfer can produce the opposite miss 8/10 times without it.',
      'External cues are superior for short-duration calibration adjustments, but the evidence is less clear for long-duration pattern construction.',
      'The Three Lab Traps: The Perfectionist, The Impatient, and The Comfort Seeker.',
      'Impact Opposites travels through all four zones: quality control (Assembly Line), compass (Crucible), emergency recalibration (Arena).',
    ],
  },
  {
    number: 7,
    title: "The Engineer's Protocol",
    summary: 'The five-station Assembly Line — a systematic blueprint for building a verified swing.',
    keyConcepts: [
      'The Proof Swing: a full-speed downswing filmed on camera that matches tour-caliber positions within 5% on Parallax — before a ball is ever struck.',
      'The Snapshot Artifact: studies measured explicit groups at their worst moment (maximum cognitive debt before consolidation) and implicit groups at steady state.',
      'Three theories independently prescribe explicit construction first: Reinvestment Theory, Transfer-Appropriate Processing, and Predictive Processing.',
      'The 5x5 standard: five consecutive reps within 5% of tour model on Parallax — the count resets on any failed rep.',
      'The J-Curve: a temporary performance decline during construction followed by eventual improvement beyond the original baseline.',
      'The Dream House Protocol: use zero mechanical thoughts on the course during the Forging Season — live in the Old House while building the Dream House in the Assembly Line.',
      'Every session starts at Station 1: running 5x5 confirmation reps on every previously passed station before advancing.',
      'The Exaggeration Principle: golfers underdeliver on correction — "too much" always feels like less movement than the camera shows.',
      'Reverse chaining: teaching the destination before the journey means every preceding step is connected to its known purpose.',
      'The Scottie Scheffler model: vertical-dominant ground force pattern — structurally safe, repeatable, and fast.',
    ],
  },
  {
    number: 8,
    title: 'The Engine',
    summary: 'Ground force mechanics — the real source of speed, power, and consistency.',
    keyConcepts: [
      '85% of amateur golfers fake their pivot. The Kickstand Test reveals whether they\'re using arms or ground force.',
      '"Pressure" not "weight": weight is passive (gravity); pressure is active (generated by pushing into the ground).',
      'The three forces of a real pivot: Linear (Shift), Rotational (Torque), Vertical (Explosion).',
      'The Ice Skater Principle: angular momentum conservation — when a rotating system gets smaller (vertical extension), rotational speed must increase.',
      'The Bullwhip: each segment (pelvis → thorax → arms → club) accelerates then decelerates to transfer energy. If the pelvis keeps accelerating, energy never transfers.',
      'Reverse chaining in Station 1: teach the Explode step first, then Load and Shift.',
      '"Turn your hips" failed because it made rotation visible but missed the violent vertical loading that preceded it.',
      'The Stretch-Shortening Cycle: lower body fires early while the thorax hangs back, eccentrically loading the obliques and thoracic rotators.',
      'The Cannon vs. Scalpel: learning the explosive Cannon first encodes the kinematic sequence which the Scalpel then runs at reduced amplitude.',
      'Station 1 graduation: Parallax Ground Force score of 80+ within 5% of tour average, full Load-Shift-Explode sequence, 1A result holding in normal stance.',
    ],
  },
  {
    number: 9,
    title: 'The Freezer',
    summary: 'Adding the club and the Four Pillars — building the delivery geometry.',
    keyConcepts: [
      'Station 1 pivot disappears when a real club is added — caused by the brain\'s threat-detection system, not the body\'s mobility.',
      'The Four Pillars (in order): Lead Wrist, Chest Turn, Trail Arm, Master Compass.',
      'The "2-for-1 Move": lead wrist flexion simultaneously closes the clubface AND shallows the plane through biomechanical coupling.',
      'The Freezer works because: slowing below the threshold of automation gives the prefrontal cortex time to see, compare, and correct.',
      'The Trigger: two simultaneous actions — Shift and Arm Drop.',
      'The Proof Swing is "base camp" — the pattern exists in the body, asking the brain to repeat something it has already done.',
      'TPI 82% correlation (toe touch failure and early extension): meaningful association but not causal.',
      '"Steep is the default setting of the human body" — the glenohumeral joint is optimized for overhead delivery, not a tilted planar swing.',
      'The Freezer Checklist on the course: silencing doubt with data — "I ran this this morning; the blueprint is verified."',
      'Early extension with a short club disappears — proving it\'s a threat response to steep geometry, not a flexibility problem.',
    ],
  },
  {
    number: 10,
    title: 'The Smoothie',
    summary: 'Bridging closed-loop construction to open-loop execution via the Tempo Ladder.',
    keyConcepts: [
      'Closed-Loop Control: the slow, deliberate, high-feedback mode running through the prefrontal cortex — used at 10 seconds on the Tempo Ladder.',
      'The Tempo Ladder rule: success = move one second faster; failure = return to the Freezer sequence immediately.',
      '"Around 3–6 seconds, something changes": the old pattern reasserts itself — this marks the exact boundary between closed-loop and open-loop transfer where learning actually occurs.',
      'The Neurological Handshake: the fast brain (basal ganglia/cerebellum) learns what the slow brain (prefrontal cortex) built.',
      'The Backswing Revelation: once the destination (Proof Swing) is established, the backswing self-organizes — it doesn\'t need to be taught, it needs to be allowed.',
      'Parameterization (Schmidt\'s Schema Theory): the Tempo Ladder calibrates the generalized motor program across a range of speeds. The oscillation builds the generalized rule.',
      'The Smoothie solved the closed-loop to open-loop gap after Proof Swing was achieved.',
      '"The learning lives in the oscillation" — deliberate alternation at the 3-second boundary is the mechanism of transfer.',
      'Station 3 graduation: Proof Swing positions at 2 seconds, ground force firing automatically at full speed, backswing self-organized.',
      'Two short sessions with a consolidation gap consistently outperform one long session — motor memories consolidate during rest.',
    ],
  },
  {
    number: 11,
    title: 'The Foamie',
    summary: 'Introducing the foam ball — stress inoculation before live ball contact.',
    keyConcepts: [
      'Foam ball primary function: stress inoculation — introducing attentional competition at a fraction of the emotional intensity of a real ball.',
      '"The foam ball is not your target. It is furniture." Attentional spotlight stays on the mechanical blueprint.',
      'Rule of 3: one miss is noise, two is coincidence, three consecutive is a pattern — only then execute one Whack with Impact Opposite.',
      'Caleb\'s protocol: one attentional channel on whether the pattern matches the blueprint outperforms ten channels split across multiple metrics.',
      '"If you actually hit great shots, you\'re probably regressing to your old swing." Early great shots mean the old attractor won.',
      'Triage Sequence order enforced: face cannot be diagnosed until path and contact are stable.',
      'Station 4 graduation: contact centered and unlit, Parallax maintained, path within ±2° — Tour Tempo verified at Station 5, NOT Station 4.',
      'Reinvestment Theory: conscious re-engagement when the foam ball appears disrupts the automated program — it\'s a threat response, not weakness.',
      'The author changed his view: single-channel construction is superior to multi-channel, data-rich practice for motor encoding.',
      'Station 4 Firewall: Freezer Checklist must confirm the blueprint held — if it drifted, the session introduced contamination.',
    ],
  },
  {
    number: 12,
    title: 'The Final Exam',
    summary: 'The live ball — trusting camera over outcome when they disagree.',
    keyConcepts: [
      '"The Battle of Two Truths": the camera confirms a perfect motion while the ball shows a terrible result — trusting process over outcome.',
      'Three Paths when camera and ball disagree: The Tinkerer\'s Retreat, The Rationalizer, The Engineer\'s Stand.',
      'The Rationalizer is more seductive than the Tinkerer — "small adjustments" still means negotiating with the old pattern.',
      'Tour Tempo (Novosel): 3:1 backswing-to-downswing ratio — nearly universal among Tour players.',
      'Return to foam ball during Station 5 when mechanics break down — not because ball flight is bad.',
      '"A perfect swing that produces a terrible shot is a perfect rep." Camera is the authority, not the ball.',
      'Station 5 introduces real consequence — requiring all prior desirable difficulties simultaneously.',
      'The Rebalancing Problem: real ball consequence increases emotional load, which competes for the attentional budget the new pattern requires.',
      '"The Handoff": a finished machine — not a finished golfer. Built and verified but not yet calibrated in variable conditions.',
      '"Silence": the mechanical chatter that required conscious supervision goes quiet, freeing the brain for course management.',
    ],
  },
  {
    number: 13,
    title: "The Warrior's Philosophy",
    summary: 'Variable practice, contextual interference, and why the forge must always exceed the fire.',
    keyConcepts: [
      'Dwight Howard\'s 32.8-point gap (82% practice / 49.2% game): the Transfer Gap — Assembly Line without Crucible.',
      'F.O.R.G.E.: Fidelity, Overload, Random, Graded, Exit.',
      'Transfer Index: ratio of Crucible/Arena performance to Lab/Assembly Line baseline.',
      'Competence Trap Hypothesis (CTH): adults (SMD=0.54) and older adults (SMD=1.28) benefit robustly from contextual interference; children benefit negligibly (SMD=0.12).',
      'Tshering from Bhutan: ten thousand consequential reps from childhood built everything — no Assembly Line needed.',
      '"The forge must always exceed the fire": practice difficulty must exceed course difficulty.',
      'Course management dogma mandates blocked practice through the stock shot philosophy — sound strategy, terrible practice architecture.',
      'The Lazy Susan experiment: blocked baseline dispersion was 20% tighter — confirming the performance-learning distinction.',
      '"Chase learning. Not performance." Variable practice looks worse but produces more durable transfer.',
      'The Honest Tension: the Assembly Line is bad for transfer but worth it — construction speed makes the trade worthwhile.',
    ],
  },
  {
    number: 14,
    title: "The Artist's Philosophy",
    summary: 'Attention, trust, and executing under pressure with S.C.O.R.E.',
    keyConcepts: [
      'The Gorilla Experiment: attention is bandwidth allocation — a genuine counting task absorbs attention better than willpower-based suppression.',
      'S.C.O.R.E.: Strategize, Commit, Observe, Reset, Engage.',
      'Trust Equation: Trust = Assembly Line + Lab + Crucible.',
      '"Grain of Sand" vs. swing thought: a Grain of Sand is a bookmark — a minimal sensory cue that holds place without loading the system.',
      'Active Inference (Friston): under pressure, the brain increases precision weighting on internal sensory feedback — de-automating the motor program it\'s trying to protect.',
      'The Three Assassins: The Ghost of the Past (Emotional Residue), The Tyrant of the Future (Outcome Obsession), The Critic in the Present (Mechanical Meddling).',
      '10-Second Reset: 2-Breath Reset (vagal activation via long exhale), Physical Trigger, Mental Trigger (one closing word).',
      '"Commitment Gate": a physical or imagined line where all analysis stops — half-commitment is the most dangerous state in competitive golf.',
      '"The counting task is only as real as the construction behind it." S.C.O.R.E. requires real preparation to generate genuine cognitive load.',
      'The "Gamer Pivot": play your miss, reduce swing speed, score with what you have today — write the Honest Note after the round.',
    ],
  },
  {
    number: 15,
    title: 'The Curious Golfer',
    summary: 'Neuroplasticity, adult learning, and why curiosity is a biological maintenance protocol.',
    keyConcepts: [
      'The Plasticity Confound: research conflated genuine biological constraint AND self-selection of inferior practice — attributing the composite to biology alone.',
      'Ray\'s fade around the oak tree: the environment builds one pattern; curiosity preserves what was never required.',
      'Older adults (SMD=1.28) benefit MOST from variable practice — the group declared most limited shows the largest gains.',
      'Around age 65–70: older adults increasingly recruit the prefrontal cortex for motor tasks younger adults run through the basal ganglia — Bucket fills faster.',
      '"Deliberate curiosity is a neurological maintenance protocol" — three-part logic: neuroscience, motor learning, and ecological dynamics.',
      'Transfer Index is the "North Star" — a golfer may improve their Mechanics Index while Mechanics Transfer stays negative.',
      'Speed Index transfer proxy: driver speed on first tee of competition vs. relaxed practice.',
      '"Architectural Override": the Assembly Line engineers an environment requiring less neuroplasticity — removing the ball eliminates the attentional loads that consume the neuroplasticity budget.',
      '"Poor Advice Problem": blocked practice produces better-looking sessions — which satisfies the student and produces a billable outcome.',
      '"Ray played golf until the year he died. That\'s the whole instruction." The practice architecture described is a decision about how the brain ages.',
    ],
  },
  {
    number: 16,
    title: 'The Architect',
    summary: 'Integrating all five personas and prescribing the right zone at the right time.',
    keyConcepts: [
      'The Architect is the "fifth persona" — doesn\'t swing a club, reads the Map, diagnoses coordinates, and routes to the correct zone before the first ball is struck.',
      'Trust Equation as diagnostic: "Which term in the equation is zero?" — identifying whether Assembly Line, Lab, or Crucible is the missing structural term.',
      'Two variables determine zone distribution: the season (Forging vs Sharpening) and the Mechanics Index gap.',
      '"The Mechanics Index gates the season transition, not the calendar."',
      'Mechanics Index above threshold + Transfer Index negative: return to Chapter 13 — stack F.O.R.G.E. levers and make practice harder than the game.',
      'Online coaching dominance: a swing change\'s critical moments happen between sessions — online coaching catches drift at rep 15 rather than rep 70.',
      '"The Great Equalizer": no ball, no range, no course, no real-time instructor required — a phone camera and a secondhand 7-iron can build a technically sound swing anywhere.',
      'The Architect\'s Mindset transfers beyond golf: separate construction from performance, trust process over outcome, pressure-test before you deploy.',
      'When the student owns the how — adherence stops being a willpower problem and becomes a process problem.',
      '"This is going to snowball" — Fosbury at the 1968 Olympics: a method that looked inefficient won gold, and by 1980 had become universal.',
    ],
  },
];
