import { CertQuestion } from './l1-questions';

export const L2_QUESTIONS: CertQuestion[] = [
  // SECTION 1: DEVELOPMENTAL FRAMEWORK (10 questions)
  {
    id: 'l2_s1_q1',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'The ICC Athletic Development Map assigns what golf-to-athletics ratio for the Regular Academy serving ages 11–14?',
    options: [
      { label: 'A', text: '50% golf / 50% athletics' },
      { label: 'B', text: '65% golf / 35% athletics' },
      { label: 'C', text: '80% golf / 20% athletics' },
      { label: 'D', text: '90% golf / 10% athletics' },
    ],
    correctAnswer: 'C',
    explanation: '80/20 for Regular Academy ages 11–14.',
  },
  {
    id: 'l2_s1_q2',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'A 13-year-old who was coordinated and technically clean at age 10 suddenly appears clumsy and is struggling with basic drills this season. What is the most likely developmental explanation?',
    options: [
      { label: 'A', text: 'He has developed a compensatory fault that needs immediate correction' },
      { label: 'B', text: 'He has not been practicing enough at home' },
      { label: 'C', text: 'Peak Height Velocity — bones have grown faster than the nervous system has adapted, temporarily disrupting established motor patterns' },
      { label: 'D', text: 'His equipment is now too small and is causing mechanical problems' },
    ],
    correctAnswer: 'C',
    explanation: 'PHV temporarily disrupts established motor patterns — this is expected, not a fault.',
  },
  {
    id: 'l2_s1_q3',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'The LTAD framework identifies which age window as the highest-leverage period for fundamental motor skill acquisition?',
    options: [
      { label: 'A', text: 'Ages 4–7' },
      { label: 'B', text: 'Ages 6–9' },
      { label: 'C', text: 'Ages 8–12' },
      { label: 'D', text: 'Ages 13–16' },
    ],
    correctAnswer: 'C',
    explanation: 'Ages 8–12 is the LTAD "Skills Window" — highest leverage for fundamental motor acquisition.',
  },
  {
    id: 'l2_s1_q4',
    section: '1',
    sectionName: 'Developmental Framework',
    question: "Why should ICC staff design sessions for a player's developmental level rather than their chronological age?",
    options: [
      { label: 'A', text: 'Chronological age groupings are required by the PGA ADM framework' },
      { label: 'B', text: 'Physical and cognitive maturity can vary by several years among children of the same birthday — designing for developmental level produces better outcomes' },
      { label: 'C', text: 'Developmental level is more easily measured than age for grouping purposes' },
      { label: 'D', text: 'Chronological age is used for competition placement; developmental level is only for practice design' },
    ],
    correctAnswer: 'B',
    explanation: 'Maturity variance of several years — designing for developmental level, not birthday, is the evidence-based standard.',
  },
  {
    id: 'l2_s1_q5',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'What does research consistently identify as the peak attrition window for youth sport dropout?',
    options: [
      { label: 'A', text: 'Ages 7–9' },
      { label: 'B', text: 'Ages 10–11' },
      { label: 'C', text: 'Ages 12–15' },
      { label: 'D', text: 'Ages 16–18' },
    ],
    correctAnswer: 'C',
    explanation: 'Ages 12–15 is the peak dropout window — the window ICC programming is specifically designed to bridge.',
  },
  {
    id: 'l2_s1_q6',
    section: '1',
    sectionName: 'Developmental Framework',
    question: "Golf's American Development Model (ADM) explicitly discourages which of the following?",
    options: [
      { label: 'A', text: 'Multi-sport participation before age 12' },
      { label: 'B', text: 'Games-based learning in junior programs' },
      { label: 'C', text: 'Quality coaching at the youngest developmental levels' },
      { label: 'D', text: 'Single-sport specialization in golf before age 10' },
    ],
    correctAnswer: 'D',
    explanation: 'ADM explicitly discourages early specialization before age 10.',
  },
  {
    id: 'l2_s1_q7',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'According to the ICC stage-transition checklist, what is the primary criterion for moving a junior from Future Stars to Junior League?',
    options: [
      { label: 'A', text: 'The junior can consistently carry the ball at least 30 yards with a junior club' },
      { label: 'B', text: 'The junior has completed the full 5-day Future Stars arc' },
      { label: 'C', text: 'Safety habits are internalized without prompting, and the junior shows genuine enthusiasm to return' },
      { label: 'D', text: 'The junior can putt with consistent Tick-Tock rhythm to a 6-foot target' },
    ],
    correctAnswer: 'C',
    explanation: 'Safety habits internalized + enthusiasm to return — not skills, not completion of a program arc.',
  },
  {
    id: 'l2_s1_q8',
    section: '1',
    sectionName: 'Developmental Framework',
    question: "A parent insists their 8-year-old daughter should skip Regular Academy and go directly to Certified Academy because she outperforms other players her age. What is your response?",
    options: [
      { label: 'A', text: 'Agree — skill level should always determine program placement' },
      { label: 'B', text: 'Run a skills assessment on the spot and decide based on what you observe' },
      { label: 'C', text: 'Explain that program readiness is assessed through the stage-transition checklist, not peer comparison, and offer to walk through the criteria together' },
      { label: 'D', text: 'Decline based on the minimum age requirement — Certified Academy requires age 13' },
    ],
    correctAnswer: 'C',
    explanation: 'Stage-transition checklist, not peer comparison — walk through the criteria together.',
  },
  {
    id: 'l2_s1_q9',
    section: '1',
    sectionName: 'Developmental Framework',
    question: 'A 9-year-old finds the Left-Right Discovery drill too easy and is visibly disengaged. The correct response is:',
    options: [
      { label: 'A', text: 'Introduce explicit face angle and path vocabulary to increase cognitive load' },
      { label: 'B', text: 'Move directly to the Crucible zone since the Lab is clearly too easy' },
      { label: 'C', text: 'Let them self-direct until they find something that interests them' },
      { label: 'D', text: 'Increase the task challenge — tighten the target, add distance, or require a specific shape — without changing the activity' },
    ],
    correctAnswer: 'D',
    explanation: 'Increase challenge within the activity — tighten target, add distance, require shape. Do not change zones or introduce vocabulary prematurely.',
  },
  {
    id: 'l2_s1_q10',
    section: '1',
    sectionName: 'Developmental Framework',
    question: "According to Piaget's framework, at what age do children first become capable of formal operational thinking — abstract reasoning and understanding hypotheticals?",
    options: [
      { label: 'A', text: 'Ages 5–7' },
      { label: 'B', text: 'Ages 8–10' },
      { label: 'C', text: 'Ages 11–12 and older' },
      { label: 'D', text: 'Ages 13–14' },
    ],
    correctAnswer: 'C',
    explanation: 'Formal operational = ages 11–12+ per Piaget. Before this window, abstract instruction is largely inaccessible.',
  },

  // SECTION 2: GUIDED ECOLOGY AND IMPACT OPPOSITES (10 questions)
  {
    id: 'l2_s2_q1',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'Standard ecological teaching fails in golf specifically because:',
    options: [
      { label: 'A', text: "Young players do not have the attention span for discovery-based learning" },
      { label: 'B', text: "Golf's feedback loop is broken — ball flight takes 3–5 seconds, impact lasts 0.0005 seconds, and players systematically misread cause and effect" },
      { label: 'C', text: 'Constraints are too complex for coaches to set up in group settings' },
      { label: 'D', text: 'Ecological teaching produces slower initial improvement, which is unacceptable in junior programs' },
    ],
    correctAnswer: 'B',
    explanation: "Golf's broken feedback loop — 0.0005 seconds of impact followed by 3–5 seconds of ball flight — makes standard ecological discovery systematically misleading.",
  },
  {
    id: 'l2_s2_q2',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: "A junior's ball consistently starts right of target and curves further right. Using the Triage Sequence, what is the first variable to address?",
    options: [
      { label: 'A', text: 'Face angle — ball starting right indicates an open face' },
      { label: 'B', text: 'Contact location — toe strikes may be causing gear effect fade' },
      { label: 'C', text: 'Path — ball starting and curving right means path is more right than face; fix path first' },
      { label: 'D', text: 'Low point — thin contact may be causing the ball to launch right' },
    ],
    correctAnswer: 'C',
    explanation: 'Ball starts right AND curves right = path is right of face. Path is the first Triage variable.',
  },
  {
    id: 'l2_s2_q3',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'What is the Primal Cue for a junior who is a chronic fat hitter (low point behind the ball)?',
    options: [
      { label: 'A', text: '"Hit the inside of the ball"' },
      { label: 'B', text: '"Hit the top of the ball"' },
      { label: 'C', text: '"Hit the dirt first"' },
      { label: 'D', text: '"Reach for the far side of the ball"' },
    ],
    correctAnswer: 'B',
    explanation: '"Hit the top of the ball" — the impact opposite of fat contact moves low point forward.',
  },
  {
    id: 'l2_s2_q4',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'A 7-year-old is hitting consistent pulls (ball starting left, minimal curve). Which instruction correctly applies Impact Opposites at this age?',
    options: [
      { label: 'A', text: '"Your face and path are both going left — we need to fix your face angle first"' },
      { label: 'B', text: '"Swing right of the flag — try to make the ball start that way"' },
      { label: 'C', text: '"Let me show you the correct grip position to keep the face square"' },
      { label: 'D', text: '"Watch my swing and copy what I do with my hands at impact"' },
    ],
    correctAnswer: 'B',
    explanation: 'Task-based, direction-focused, no vocabulary — exactly right for age 7. Motor system responds to the task.',
  },
  {
    id: 'l2_s2_q5',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'What does the Rule of 3 govern in the Impact Opposites protocol?',
    options: [
      { label: 'A', text: 'A player must produce the opposite miss on 3 consecutive attempts before the constraint is removed' },
      { label: 'B', text: 'Each session must include 3 sets of Impact Opposites work before moving to other activities' },
      { label: 'C', text: 'A pattern is confirmed after 3 consecutive misses in the same direction — one or two misses are noise' },
      { label: 'D', text: 'The constraint must stay in place for a minimum of 3 sessions regardless of player response' },
    ],
    correctAnswer: 'C',
    explanation: '3 consecutive same-direction misses = confirmed pattern. 1 or 2 are noise.',
  },
  {
    id: 'l2_s2_q6',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'A junior scores 4 on the Opposite Miss Challenge (4 successful opposite misses out of 10). What is the correct next step?',
    options: [
      { label: 'A', text: 'Move to the Assembly Line — a score below 5 indicates a construction problem' },
      { label: 'B', text: 'Move to tee-only stage — any response shows the motor system is reachable' },
      { label: 'C', text: 'Increase the constraint and increase the exaggeration. Two more sessions of full exaggeration. Do not taper. Retest.' },
      { label: 'D', text: 'Switch to a different bias pattern — this one is proving too resistant' },
    ],
    correctAnswer: 'C',
    explanation: 'Score below 5 = increase constraint and exaggeration, two full sessions, no taper, retest.',
  },
  {
    id: 'l2_s2_q7',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'Impact Opposites at ICC begins at age:',
    options: [
      { label: 'A', text: '9 — when players have developed sufficient ball flight awareness' },
      { label: 'B', text: '11 — when formal operational thinking enables diagnostic reasoning' },
      { label: 'C', text: '7 — task-based delivery works through the motor system regardless of vocabulary' },
      { label: 'D', text: '13 — when players can engage with the full Primal Cue protocol' },
    ],
    correctAnswer: 'C',
    explanation: 'Age 7 — task-based delivery bypasses vocabulary requirements entirely.',
  },
  {
    id: 'l2_s2_q8',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'What is the correct 3-stage Impact Opposites progression?',
    options: [
      { label: 'A', text: 'Clean lie → tee → constraint + tee' },
      { label: 'B', text: 'Tee only → constraint → clean lie' },
      { label: 'C', text: 'Constraint + tee → tee only → clean lie on grass' },
      { label: 'D', text: 'Clean lie → constraint → tee only' },
    ],
    correctAnswer: 'C',
    explanation: 'Constraint + tee first (maximum support), then tee only (remove constraint), then clean lie (full transfer).',
  },
  {
    id: 'l2_s2_q9',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'The Hit-Guess-Look protocol is primarily a tool for:',
    options: [
      { label: 'A', text: 'Diagnosing swing path direction using ball flight curvature patterns' },
      { label: 'B', text: "Calibrating a player's contact perception — closing the gap between what they feel and what is actually happening on the face" },
      { label: 'C', text: 'Teaching players to predict where their ball will land before it stops rolling' },
      { label: 'D', text: 'Building the habit of watching ball flight instead of the club at impact' },
    ],
    correctAnswer: 'B',
    explanation: 'Hit-Guess-Look calibrates contact perception — feel vs. reality gap.',
  },
  {
    id: 'l2_s2_q10',
    section: '2',
    sectionName: 'Guided Ecology and Impact Opposites',
    question: 'Why does the ICC curriculum use task-based language ("make it curve that way") for Impact Opposites work with ages 7–8, rather than named concepts like "face angle" or "path"?',
    options: [
      { label: 'A', text: 'Younger players cannot understand cause and effect before age 9' },
      { label: 'B', text: 'The task-based approach avoids building technical vocabulary too early' },
      { label: 'C', text: 'The motor system responds to the task — physical experience must come before vocabulary, not the reverse' },
      { label: 'D', text: 'Named concepts are trademarked in The Golf Textbook and restricted to older learners' },
    ],
    correctAnswer: 'C',
    explanation: 'Motor system responds to task first — vocabulary must follow experience, not precede it.',
  },

  // SECTION 3: SESSION DESIGN — FITNESS, WARM-UP, AND ZONE STRUCTURE (10 questions)
  {
    id: 'l2_s3_q1',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'How are most ICC fitness block repetitions scaled?',
    options: [
      { label: 'A', text: 'All juniors do 10 reps regardless of age or ability' },
      { label: 'B', text: 'The instructor assigns reps based on observed fitness level in the session' },
      { label: 'C', text: 'Reps scale by 5 every two weeks throughout the program season' },
      { label: 'D', text: 'One rep per year of age — a 10-year-old does 10 reps' },
    ],
    correctAnswer: 'D',
    explanation: 'One rep per year of age — simple, automatic, developmental.',
  },
  {
    id: 'l2_s3_q2',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'Why do ball throws in the fitness block use a fixed count of 10 per hand rather than the age-scaling rule?',
    options: [
      { label: 'A', text: 'Throwing is low-intensity and benefits from higher reps at all ages' },
      { label: 'B', text: 'Bilateral development requires enough reps to feel the difference between hands — fewer than 10 is insufficient' },
      { label: 'C', text: '10 is the average for the primary age range of the program' },
      { label: 'D', text: 'The age-scaling rule only applies to golf-specific exercises in the sequence' },
    ],
    correctAnswer: 'B',
    explanation: 'Bilateral development needs enough reps to notice the inter-hand difference — 10 is the minimum effective dose.',
  },
  {
    id: 'l2_s3_q3',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'What is the correct 360 Jump progression order?',
    options: [
      { label: 'A', text: '360° → 180° → 90° — start big, refine to smaller rotations' },
      { label: 'B', text: '180° → 360° → 90° — begin with the most common challenge' },
      { label: 'C', text: '90° → 180° → 360° — establish landing stability before adding rotation' },
      { label: 'D', text: 'All three levels simultaneously — players self-select their appropriate level' },
    ],
    correctAnswer: 'C',
    explanation: '90° first — establish landing stability, then build rotation.',
  },
  {
    id: 'l2_s3_q4',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'Why do Freezers and Smoothies in the warm-up use a fixed count of 10 reps for all ages?',
    options: [
      { label: 'A', text: 'Younger players need more repetitions of Assembly Line work to compensate for shorter attention spans' },
      { label: 'B', text: 'The Golf Textbook sets 10 as the standard for all Assembly Line protocols' },
      { label: 'C', text: 'The rep count reflects what the movement requires to consolidate, not athletic capacity — 10 is the pattern-building standard' },
      { label: 'D', text: 'Freezers and Smoothies are too advanced for younger players so the count is fixed to avoid scaling issues' },
    ],
    correctAnswer: 'C',
    explanation: 'Pattern-building standard, not athletic capacity — the movement needs 10 to consolidate.',
  },
  {
    id: 'l2_s3_q5',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'What is the primary motor learning benefit of Name Writing with the clubhead in the warm-up sequence?',
    options: [
      { label: 'A', text: 'It checks that juniors remember their grip setup from the previous session' },
      { label: 'B', text: 'It builds intrinsic hand strength and proprioceptive sensitivity through grip without any direct instruction about grip pressure' },
      { label: 'C', text: 'It provides a confidence-building low-stakes activity before hitting begins' },
      { label: 'D', text: 'It serves as a developmental assessment of fine motor skills for age grouping purposes' },
    ],
    correctAnswer: 'B',
    explanation: 'Proprioceptive sensitivity without instruction — grip pressure emerges from the task.',
  },
  {
    id: 'l2_s3_q6',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'According to the Four Zone framework, a Future Stars session should be approximately:',
    options: [
      { label: 'A', text: '50% Assembly Line / 50% Lab — equal construction and calibration' },
      { label: 'B', text: '70% Assembly Line / 30% Crucible — build first, compete second' },
      { label: 'C', text: '90% Lab / 10% Arena — discover first, play second' },
      { label: 'D', text: '40% Lab / 40% Crucible / 20% Arena — fully scaled version of the adult map' },
    ],
    correctAnswer: 'C',
    explanation: '90% Lab / 10% Arena for Future Stars — pure discovery with a tiny taste of real play.',
  },
  {
    id: 'l2_s3_q7',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'You are running an Academy session and the Freezer block is not complete when the 30-minute range mark arrives. What do you do?',
    options: [
      { label: 'A', text: 'Move to short game on schedule — the 30/30 split is fixed and non-negotiable' },
      { label: 'B', text: 'Finish the Freezer block. Shorten a short game competition format to compensate — the Freezer block is non-negotiable.' },
      { label: 'C', text: 'Skip the remaining Freezers and double them at the next session' },
      { label: 'D', text: 'Complete only one more minute of Freezers as a compromise, then transition' },
    ],
    correctAnswer: 'B',
    explanation: 'Freezer block is non-negotiable. Shorten competition formats to compensate, never skip Freezers.',
  },
  {
    id: 'l2_s3_q8',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'The Noodle Strike warm-up drill moves from stationary to moving. What is the primary reason for the moving phase?',
    options: [
      { label: 'A', text: 'Moving targets develop throwing mechanics that directly transfer to full swing athleticism' },
      { label: 'B', text: 'Each swing becomes a new motor problem — variable practice produces more durable skill than repeated identical swings' },
      { label: 'C', text: 'Moving targets prepare players for on-course wind and lie variation' },
      { label: 'D', text: 'It increases session energy by introducing a competitive element between partners' },
    ],
    correctAnswer: 'B',
    explanation: 'Variable practice — each swing is a new motor problem, producing more durable skill than blocked repetition.',
  },
  {
    id: 'l2_s3_q9',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'In the Academy session, what is the variable practice rule that applies to both putting and chipping stations?',
    options: [
      { label: 'A', text: 'Players must change clubs every five shots to avoid groove dependence' },
      { label: 'B', text: 'Players rotate between putting and chipping every 8 minutes' },
      { label: 'C', text: 'Never hit the same target twice in a row — change targets between every shot' },
      { label: 'D', text: 'Players must vary their distance from the target by at least 3 feet between consecutive shots' },
    ],
    correctAnswer: 'C',
    explanation: 'Never the same target twice in a row — this is the universal ICC variable practice standard.',
  },
  {
    id: 'l2_s3_q10',
    section: '3',
    sectionName: 'Session Design — Fitness, Warm-Up, and Zone Structure',
    question: 'The Survivor range game eliminates players across three escalating rounds. What is the correct Round 1 standard?',
    options: [
      { label: 'A', text: 'Ball must carry past the first range flag' },
      { label: 'B', text: 'Player must hit an intentional draw or fade as called' },
      { label: 'C', text: 'Player must land the ball within 20 yards of a target' },
      { label: 'D', text: 'Player must finish in balance — an unbalanced finish results in elimination' },
    ],
    correctAnswer: 'D',
    explanation: 'Round 1 = balance check. Finish unbalanced = out.',
  },

  // SECTION 4: THE CONSTRAINTS TOOLKIT (8 questions)
  {
    id: 'l2_s4_q1',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'What is the core principle of the Constraints-Led Approach?',
    options: [
      { label: 'A', text: 'The coach prescribes the correct positions and the student practices replicating them' },
      { label: 'B', text: 'Constraints are used only after verbal instruction has failed to produce a change' },
      { label: 'C', text: 'Manipulating task and environmental constraints makes the desired movement the path of least resistance — the motor system self-organizes without direct instruction' },
      { label: 'D', text: 'Physical constraints build discipline and attention by adding consequence to practice' },
    ],
    correctAnswer: 'C',
    explanation: 'Path of least resistance — the motor system self-organizes. No direct instruction required.',
  },
  {
    id: 'l2_s4_q2',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'A junior is hitting consistent heel strikes. You place a small piece of tape on the toe of the club as a target zone. What type of constraint is this and what is it intended to do?',
    options: [
      { label: 'A', text: 'Avoidance constraint — the junior must avoid hitting the tape' },
      { label: 'B', text: 'Avoidance constraint — the tape creates a boundary that forces the path inside' },
      { label: 'C', text: 'Target constraint — the junior aims to strike the tape zone to move contact toward the toe' },
      { label: 'D', text: 'Target constraint — the tape marks the center of the face as a reference point' },
    ],
    correctAnswer: 'C',
    explanation: 'Target constraint — aim for the tape zone to move contact away from the heel toward the toe.',
  },
  {
    id: 'l2_s4_q3',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'When should you move from Stage 1 (constraint active) to Stage 2 (constraint adjacent) in the ICC progression protocol?',
    options: [
      { label: 'A', text: 'When the student requests to try without the constraint' },
      { label: 'B', text: 'After one successful repetition without contacting the constraint' },
      { label: 'C', text: 'After 10 minutes of work with the constraint in place' },
      { label: 'D', text: 'When the student executes the correct pattern without contacting the constraint on 7 of 10 attempts' },
    ],
    correctAnswer: 'D',
    explanation: '7 of 10 clean attempts — specific threshold before removing the physical guide.',
  },
  {
    id: 'l2_s4_q4',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'The headcover-behind-the-right-toe constraint is designed to address which fault?',
    options: [
      { label: 'A', text: 'Out-to-in path producing a pull-slice' },
      { label: 'B', text: 'Steep attack angle producing fat contact' },
      { label: 'C', text: 'Heel strikes caused by standing too close to the ball' },
      { label: 'D', text: 'Open face / early release — swinging over the headcover delays the release and allows the face to square' },
    ],
    correctAnswer: 'D',
    explanation: 'Headcover behind right toe = delays release, allows face to square. Targets open face / early release.',
  },
  {
    id: 'l2_s4_q5',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: "You place an outside noodle path guard for a junior with an out-to-in path. After 8 swings she has not hit the noodle, but her ball flight has not changed. What is most likely happening?",
    options: [
      { label: 'A', text: 'The constraint is working but needs more time — continue for another 10 swings' },
      { label: 'B', text: "The noodle is not positioned to intercept her actual downswing path — reposition it closer and inside her current path" },
      { label: 'C', text: 'The ball flight problem is face-related, not path-related — switch to a face constraint' },
      { label: 'D', text: 'Verbal instruction is needed — constraints are not effective for this player type' },
    ],
    correctAnswer: 'B',
    explanation: 'Not intercepting the path = noodle is positioned wrong. Reposition closer and inside the actual downswing.',
  },
  {
    id: 'l2_s4_q6',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'When is it appropriate to use a launch monitor as a constraint rather than purely as feedback?',
    options: [
      { label: 'A', text: 'Any time a player is curious about their numbers' },
      { label: 'B', text: 'Only after all verbal cues and physical constraints have failed' },
      { label: 'C', text: 'When the player is given a specific numerical target before the swing, swings freely toward an external cue, and checks the screen after — never during' },
      { label: 'D', text: 'Only with players 15 and older who have the technical vocabulary to interpret the data' },
    ],
    correctAnswer: 'C',
    explanation: 'Target before, swing freely, check after — never during. This is the constraint use protocol.',
  },
  {
    id: 'l2_s4_q7',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'What is the correct age floor for pool noodles on alignment rods as a plane constraint?',
    options: [
      { label: 'A', text: 'Ages 4+ — any child who can swing a club' },
      { label: 'B', text: 'Ages 7–9 using a noodle on the ground; progressing to noodle on rod from age 10' },
      { label: 'C', text: 'Ages 13+ only — younger players cannot process the spatial reasoning required' },
      { label: 'D', text: 'Ages 10+ across all constraint types' },
    ],
    correctAnswer: 'B',
    explanation: 'Ground noodle from age 7, rod-elevated noodle from age 10.',
  },
  {
    id: 'l2_s4_q8',
    section: '4',
    sectionName: 'The Constraints Toolkit',
    question: 'A tee placed just outside the ball on the far side from the player (not the student\'s side) addresses which contact bias?',
    options: [
      { label: 'A', text: 'Toe strikes' },
      { label: 'B', text: 'Thin contact' },
      { label: 'C', text: 'Heel strikes' },
      { label: 'D', text: 'Fat contact' },
    ],
    correctAnswer: 'C',
    explanation: 'Tee on the far side = heel strikes. Hitting the tee means you came too far inside (heel path).',
  },

  // SECTION 5: SAFETY, ETIQUETTE, AND COURSE CONDUCT (8 questions)
  {
    id: 'l2_s5_q1',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'A junior is slowly rotating their club while you are giving instruction. What is the correct response?',
    options: [
      { label: 'A', text: 'Stop instruction entirely until they set the club down completely' },
      { label: 'B', text: 'Take the club from them temporarily to remove the distraction' },
      { label: 'C', text: 'Calmly say "Club like a cane, please" and continue the instruction' },
      { label: 'D', text: 'Continue instruction — minor movement during listening is developmentally normal and acceptable' },
    ],
    correctAnswer: 'C',
    explanation: '"Club like a cane" — one calm phrase, then continue. No interruption of instruction, no taking clubs.',
  },
  {
    id: 'l2_s5_q2',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'The three non-negotiables in the ICC safety framework — behaviors that must never be waived regardless of age or context — are:',
    options: [
      { label: 'A', text: 'Circle of Safety, No running on course, No talking during swings' },
      { label: 'B', text: 'Circle of Safety, Club as Cane when listening, Eyes on instructor' },
      { label: 'C', text: 'Force Field, Equipment check before every session, Sunscreen application' },
      { label: 'D', text: 'Club as Cane, No throwing clubs, Designated hitting stations' },
    ],
    correctAnswer: 'B',
    explanation: 'The three non-negotiables: Circle of Safety, Club as Cane, Eyes on instructor.',
  },
  {
    id: 'l2_s5_q3',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: "According to ICC's lightning/weather protocol, when does outdoor activity stop?",
    options: [
      { label: 'A', text: 'When lightning is visible within 1 mile of the facility' },
      { label: 'B', text: 'When precipitation begins — rain indicates electrical activity nearby' },
      { label: 'C', text: 'When the weather horn sounds — move immediately, do not wait for club announcement or lead instructor direction' },
      { label: 'D', text: 'When the lead instructor makes the call based on current conditions' },
    ],
    correctAnswer: 'C',
    explanation: 'Horn sounds = move. No waiting, no assessment, no lead instructor direction needed.',
  },
  {
    id: 'l2_s5_q4',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'At what age should divot repair and ball mark fixing be explicitly taught in ICC programs?',
    options: [
      { label: 'A', text: 'Ages 4–6 in Future Stars — the earlier the better' },
      { label: 'B', text: 'Ages 7–10 in Junior League — the first window where course ownership is developmentally appropriate' },
      { label: 'C', text: 'Ages 11–14 in Regular Academy — when players can understand the consequences' },
      { label: 'D', text: 'Ages 15+ in Certified Academy — when players are on the full regulation course' },
    ],
    correctAnswer: 'B',
    explanation: 'Ages 7–10 / Junior League — first window where course ownership is developmentally appropriate.',
  },
  {
    id: 'l2_s5_q5',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'The ICC thrown club protocol is:',
    options: [
      { label: 'A', text: 'Play stops. Junior picks up the club. One calm sentence: "We don\'t throw clubs. Ever." Resume.' },
      { label: 'B', text: 'Junior sits out one hole. Lead instructor is notified. Parent contacted after session.' },
      { label: 'C', text: 'Junior receives a formal warning. Second offense results in removal from the session.' },
      { label: 'D', text: 'Give the junior 60 seconds to cool down, then address the behavior privately' },
    ],
    correctAnswer: 'A',
    explanation: 'Stop, pick up, one sentence, resume. No delay, no escalation on first offense.',
  },
  {
    id: 'l2_s5_q6',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'The maximum student-to-staff ratio for ages 4–6 without a helper present is:',
    options: [
      { label: 'A', text: '1 staff to 4 students' },
      { label: 'B', text: '1 staff to 6 students' },
      { label: 'C', text: '1 staff to 8 students' },
      { label: 'D', text: '1 staff to 10 students' },
    ],
    correctAnswer: 'B',
    explanation: '1:6 for ages 4–6 without helper. Above 6 requires a second staff or helper.',
  },
  {
    id: 'l2_s5_q7',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: "What is ICC's \"car ride rule\" for parent communication?",
    options: [
      { label: 'A', text: "Parents should debrief the session with their child on the drive home while the material is still fresh" },
      { label: 'B', text: 'Parents should not ask about scores during the car ride — only about effort and enjoyment' },
      { label: 'C', text: 'For the first 10 minutes after a session, no golf talk — let the child lead the conversation' },
      { label: 'D', text: 'Staff should text parents a brief update before families reach their cars' },
    ],
    correctAnswer: 'C',
    explanation: 'No golf talk for 10 minutes. Child leads the conversation.',
  },
  {
    id: 'l2_s5_q8',
    section: '5',
    sectionName: 'Safety, Etiquette, and Course Conduct',
    question: 'Which etiquette concept is developmentally appropriate to introduce at ages 4–6?',
    options: [
      { label: 'A', text: 'Signing a scorecard and understanding the legal consequences of incorrect scores' },
      { label: 'B', text: 'Out-of-bounds procedures and penalty area drop options' },
      { label: 'C', text: 'Raking bunkers after every shot as a standard expectation' },
      { label: 'D', text: 'Be quiet when someone is swinging — freeze and be silent' },
    ],
    correctAnswer: 'D',
    explanation: 'Freeze and be silent — this is the age 4–6 floor. Everything else requires higher cognitive load.',
  },

  // SECTION 6: PROGRAM-SPECIFIC KNOWLEDGE (10 questions)
  {
    id: 'l2_s6_q1',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'What are the Future Stars session format specifications?',
    options: [
      { label: 'A', text: '45 minutes, max 12 students, 1 instructor' },
      { label: 'B', text: '60 minutes, max 8 students, 2 instructors' },
      { label: 'C', text: '30 minutes, max 10 students, 2 instructors' },
      { label: 'D', text: '30 minutes, max 6 students, 1 instructor' },
    ],
    correctAnswer: 'C',
    explanation: '30 minutes, max 10 students, 2 instructors.',
  },
  {
    id: 'l2_s6_q2',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'What does the Future Stars cue "Glue the Sandwich" refer to?',
    options: [
      { label: 'A', text: 'The putting grip — thumbs together and pointing down toward the ground' },
      { label: 'B', text: 'The finish position — trailing foot sole visible behind' },
      { label: 'C', text: 'The putting stance — feet close together like a sandwich' },
      { label: 'D', text: 'The full swing grip — both hands touching with no gaps between them' },
    ],
    correctAnswer: 'D',
    explanation: '"Glue the Sandwich" = full swing grip, both hands touching with no gaps.',
  },
  {
    id: 'l2_s6_q3',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'In Future Stars Day 2, the putting drill specifies that players should never hit the same target twice in a row. What motor learning principle does this apply?',
    options: [
      { label: 'A', text: 'Massed practice — building a groove through repetition' },
      { label: 'B', text: 'Variable practice — forcing recalibration between every shot produces more durable skill than blocked repetition' },
      { label: 'C', text: 'Blocked practice — the targets change but the skill is the same' },
      { label: 'D', text: 'Random practice — removing all structure to maximize creativity' },
    ],
    correctAnswer: 'B',
    explanation: 'Variable practice — forced recalibration between shots. Blocked repetition produces groove, not durability.',
  },
  {
    id: 'l2_s6_q4',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'Future Stars Day 4 includes the Step-Swing ("Baseball Style") drill. What is the motor learning rationale?',
    options: [
      { label: 'A', text: 'The stepping motion builds cardiovascular fitness during the session' },
      { label: 'B', text: 'Athletic footwork sequences the lower body before the upper body — load before unload — without mechanical instruction' },
      { label: 'C', text: 'The step adds difficulty to maintain engagement for students who have mastered basic swings' },
      { label: 'D', text: 'Baseball mechanics are more intuitive than golf mechanics for children under 7' },
    ],
    correctAnswer: 'B',
    explanation: 'Lower before upper, load before unload — athletic sequencing without a word of mechanical instruction.',
  },
  {
    id: 'l2_s6_q5',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'The "Ring of Fire" activity in Future Stars Day 5 is described as a "Crucible-level experience delivered through play." What makes it Crucible-level?',
    options: [
      { label: 'A', text: 'It involves elimination and clear consequence for the losing player' },
      { label: 'B', text: 'It uses physical constraints to force a specific ball flight shape' },
      { label: 'C', text: 'Players perform a skill simultaneously while others are competing — performance under distraction builds robustness' },
      { label: 'D', text: 'It requires players to use a club they have not practiced with' },
    ],
    correctAnswer: 'C',
    explanation: 'Performance under distraction — skill is tested while others compete simultaneously.',
  },
  {
    id: 'l2_s6_q6',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'In the Academy chipping station, what is the correct ball position?',
    options: [
      { label: 'A', text: 'Forward of center, aligned with the lead foot' },
      { label: 'B', text: 'Back of center to encourage ball-first contact' },
      { label: 'C', text: 'Middle of stance' },
      { label: 'D', text: 'Aligned with the trail foot for maximum shaft lean' },
    ],
    correctAnswer: 'C',
    explanation: 'Middle of stance for the Academy chipping station.',
  },
  {
    id: 'l2_s6_q7',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'The Academy game "21" awards how many points for a holed chip?',
    options: [
      { label: 'A', text: '1 point — same as a close miss' },
      { label: 'B', text: '2 points — same as the closest non-holed shot' },
      { label: 'C', text: '4 points — double the standard shot value' },
      { label: 'D', text: '3 points — a premium for the best possible outcome' },
    ],
    correctAnswer: 'D',
    explanation: '3 points for a holed chip in the game of 21.',
  },
  {
    id: 'l2_s6_q8',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'What unlocks for a junior who completes ICC Junior Player Certification?',
    options: [
      { label: 'A', text: 'Eligibility to compete in USGA junior events' },
      { label: 'B', text: 'Automatic enrollment in the Certified Academy program' },
      { label: 'C', text: 'Independent course access at Interlachen AND eligibility to join Certified Academy groups' },
      { label: 'D', text: 'A junior handicap registration through the USGA' },
    ],
    correctAnswer: 'C',
    explanation: 'Independent course access at Interlachen + Certified Academy eligibility.',
  },
  {
    id: 'l2_s6_q9',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'What is the Step 2 standard for ICC Junior Player Certification?',
    options: [
      { label: 'A', text: 'Shoot 55 or better in three separate rounds witnessed by a parent' },
      { label: 'B', text: 'Complete a skills assessment with Nick Dittrick covering ball flight, course management, and etiquette' },
      { label: 'C', text: 'Shoot 55 or better on 9 holes from the forward tees with an ICC professional present — that signed scorecard is the certification document' },
      { label: 'D', text: 'Shoot 55 or better in a round and submit three parent-signed qualifying scorecards together' },
    ],
    correctAnswer: 'C',
    explanation: '55 or better on 9 holes with ICC professional present — the signed scorecard is the certification document.',
  },
  {
    id: 'l2_s6_q10',
    section: '6',
    sectionName: 'Program-Specific Knowledge',
    question: 'According to ICC staff operations, how far in advance should the ForeTees reminder email be sent to parents?',
    options: [
      { label: 'A', text: '24 hours before the session' },
      { label: 'B', text: '7 days before the session' },
      { label: 'C', text: '3 days before the session' },
      { label: 'D', text: 'The morning of the session' },
    ],
    correctAnswer: 'C',
    explanation: '3 days before the session.',
  },

  // SECTION 7: STAFF OPERATIONS AND PROFESSIONAL STANDARDS (6 questions)
  {
    id: 'l2_s7_q1',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'ICC appearance standards require which of the following for all staff during program hours?',
    options: [
      { label: 'A', text: 'ICC shirts worn untucked for comfort during active sessions; hat in any direction' },
      { label: 'B', text: 'Clean shave or well-groomed facial hair, ICC shirts tucked in, hat brim forward' },
      { label: 'C', text: 'Any golf attire that is clean and presentable; appearance is flexible during junior programs' },
      { label: 'D', text: 'ICC shirts tucked in and hat forward; facial hair standards apply only to lead instructors' },
    ],
    correctAnswer: 'B',
    explanation: 'Tucked shirt, hat forward, groomed facial hair — all staff, no exceptions.',
  },
  {
    id: 'l2_s7_q2',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'The range rope and ball supply must be confirmed ready by what time on Mondays?',
    options: [
      { label: 'A', text: '9:00am' },
      { label: 'B', text: 'At least 15 minutes before the first class' },
      { label: 'C', text: '8:40am' },
      { label: 'D', text: 'When the first family arrives' },
    ],
    correctAnswer: 'C',
    explanation: '8:40am Monday — range rope and ball supply confirmed ready.',
  },
  {
    id: 'l2_s7_q3',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'A parent approaches with a billing concern about their program enrollment. What is the correct handling?',
    options: [
      { label: 'A', text: "Address it as best you can — resolving parent concerns promptly is part of every staff member's role" },
      { label: 'B', text: 'Direct to Nick Dittrick — program administration questions go through the program coordinator' },
      { label: 'C', text: 'Direct to Luke Benoit or Blaize immediately — billing and enrollment concerns are not for field staff to resolve' },
      { label: 'D', text: 'Tell them to call the Pro Shop and provide the number: 952-929-1661' },
    ],
    correctAnswer: 'C',
    explanation: 'Luke Benoit or Blaize — billing and enrollment go directly to leadership, not field staff.',
  },
  {
    id: 'l2_s7_q4',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'ICC email communication to parents requires which of the following?',
    options: [
      { label: 'A', text: 'First-name basis — informal communication builds rapport with families' },
      { label: 'B', text: 'Mr. or Mrs. [Last Name] in formal written correspondence' },
      { label: 'C', text: 'Email is optional — most parent communication should be verbal at pickup' },
      { label: 'D', text: 'Emails should always be copied to Nick Dittrick for program records' },
    ],
    correctAnswer: 'B',
    explanation: 'Mr. or Mrs. [Last Name] — formal written standard for all parent email.',
  },
  {
    id: 'l2_s7_q5',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'If a junior is injured during a session — struck by a club or ball — what is the correct notification sequence?',
    options: [
      { label: 'A', text: 'Contact the parent, then complete the incident report, then notify Luke Benoit' },
      { label: 'B', text: 'Stop the session, assess the junior, contact the parent if beyond a minor scrape, notify Luke Benoit the same day at 612-275-2321, complete an incident report before leaving' },
      { label: 'C', text: 'Contact Luke Benoit first, then assess the junior, then contact the parent' },
      { label: 'D', text: 'Complete the incident report during the session, then contact the parent, then notify Luke Benoit' },
    ],
    correctAnswer: 'B',
    explanation: 'Stop → assess → parent contact → Luke same day → incident report before leaving.',
  },
  {
    id: 'l2_s7_q6',
    section: '7',
    sectionName: 'Staff Operations and Professional Standards',
    question: 'What does ICC track to measure junior program health year-over-year?',
    options: [
      { label: 'A', text: 'Individual handicap progression, tournament results, and win/loss records by program' },
      { label: 'B', text: 'Total juniors enrolled by program, total hours of instruction delivered, and comparison to prior year and peer private clubs' },
      { label: 'C', text: 'Certified Academy graduation rates and Junior Player Certification pass rates only' },
      { label: 'D', text: 'Parent satisfaction scores from post-session surveys' },
    ],
    correctAnswer: 'B',
    explanation: 'Enrollment, hours, year-over-year comparison, peer club benchmarking — the three-part health metric.',
  },

  // SECTION 8: MOTIVATION, PSYCHOLOGY, AND PARENT COMMUNICATION (8 questions)
  {
    id: 'l2_s8_q1',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'Self-Determination Theory identifies three basic psychological needs that drive long-term motivation. They are:',
    options: [
      { label: 'A', text: 'Competence, achievement, and recognition' },
      { label: 'B', text: 'Autonomy, competence, and relatedness' },
      { label: 'C', text: 'Belonging, challenge, and purpose' },
      { label: 'D', text: 'Mastery, autonomy, and social connection' },
    ],
    correctAnswer: 'B',
    explanation: 'SDT: Autonomy, Competence, Relatedness — the three non-negotiable drivers.',
  },
  {
    id: 'l2_s8_q2',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'A mastery climate is characterized by:',
    options: [
      { label: 'A', text: 'Removing all competitive elements so no player feels the pressure of being compared' },
      { label: 'B', text: 'Ranking and outcome as the primary public measures of session success' },
      { label: 'C', text: 'Improvement and effort being what gets celebrated — failure is treated as information, not verdict' },
      { label: 'D', text: 'External rewards (candy, prizes) for top performers to incentivize effort' },
    ],
    correctAnswer: 'C',
    explanation: 'Mastery climate: improvement + effort celebrated. Failure = information. Competition is allowed — the framing is what changes.',
  },
  {
    id: 'l2_s8_q3',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'According to the ICC Junior Golf Hierarchy of Needs, which level must be stable before a child can develop competence?',
    options: [
      { label: 'A', text: 'Autonomy — feeling in control of their own development' },
      { label: 'B', text: 'Mastery and identity — seeing themselves as a golfer' },
      { label: 'C', text: 'Social belonging — feeling connected to the peer group' },
      { label: 'D', text: 'Safety and connection — the amygdala must be calm before the prefrontal cortex engages with learning' },
    ],
    correctAnswer: 'D',
    explanation: 'Safety and connection first — the amygdala threat response blocks all higher-order learning.',
  },
  {
    id: 'l2_s8_q4',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'Research on autonomy-supportive coaching environments shows they produce athletes who are:',
    options: [
      { label: 'A', text: 'More technically skilled due to higher quality instruction time' },
      { label: 'B', text: 'Less competitive because performance pressure is reduced' },
      { label: 'C', text: 'Better suited for individual sports than team formats' },
      { label: 'D', text: 'More intrinsically motivated, more persistent, more likely to develop life skills, and significantly less likely to drop out' },
    ],
    correctAnswer: 'D',
    explanation: 'Intrinsically motivated, persistent, life skills developed, dramatically lower dropout — the full SDT evidence base.',
  },
  {
    id: 'l2_s8_q5',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'The correct ICC post-session parent communication template is:',
    options: [
      { label: 'A', text: 'One thing the child needs to improve + one drill to practice at home' },
      { label: 'B', text: 'A score or ranking compared to other juniors + the primary focus for next week' },
      { label: 'C', text: 'One specific thing the child did well + one thing the program is working on + one optional support action for home' },
      { label: 'D', text: 'A brief summary of activities covered + whether the child met the session benchmarks' },
    ],
    correctAnswer: 'C',
    explanation: 'Did well + working on + optional home action — three parts, mastery-framed, no ranking.',
  },
  {
    id: 'l2_s8_q6',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'A 13-year-old player who was enthusiastic two weeks ago now appears withdrawn — minimal effort, short answers, declining to join the putting game. What is your first action?',
    options: [
      { label: 'A', text: 'Increase competitive stakes to re-engage — disengagement often looks like boredom and responds to challenge' },
      { label: 'B', text: 'Contact their parent to ask if something is happening at home' },
      { label: 'C', text: 'Challenge them publicly in a positive way during the session to snap them out of the withdrawal' },
      { label: 'D', text: 'Speak to them privately after the session: "I\'ve noticed you seem off the last couple weeks — everything okay?" Address the person before the player.' },
    ],
    correctAnswer: 'D',
    explanation: 'Person before player — private, after the session, no performance pressure attached.',
  },
  {
    id: 'l2_s8_q7',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'A junior says "I\'m just not good at this" after a difficult session. Which response best reflects a mastery climate?',
    options: [
      { label: 'A', text: "You're doing great — everyone struggles at the beginning." },
      { label: 'B', text: "Golf is genuinely hard. Keep working and it will come." },
      { label: 'C', text: "You're better than you think — I've seen much worse." },
      { label: 'D', text: "You've improved a lot since your first session. Three weeks ago you couldn't chip to the near circle — today you made two." },
    ],
    correctAnswer: 'D',
    explanation: 'Specific, observable, individual improvement — the only response that actually addresses the belief rather than reassuring it away.',
  },
  {
    id: 'l2_s8_q8',
    section: '8',
    sectionName: 'Motivation, Psychology, and Parent Communication',
    question: 'During a four-day camp Crucible session, a junior misses four shots in a row and begins to shut down — flat affect, refusing to engage. What is the correct response?',
    options: [
      { label: 'A', text: 'Tell them competitive composure is part of sport and they need to push through it' },
      { label: 'B', text: 'Remove them from the competition and give them a non-competitive task for the remainder' },
      { label: 'C', text: 'Validate the difficulty, reset the challenge to a level where success is possible, and gradually rebuild pressure from there' },
      { label: 'D', text: 'End the Crucible session early to avoid further discouragement across the group' },
    ],
    correctAnswer: 'C',
    explanation: 'Validate → reset to achievable → rebuild pressure gradually. Keep them in, lower the floor, restore momentum.',
  },
];

export const L2_SECTIONS = [
  { id: '1', name: 'Developmental Framework', maxPoints: 10 },
  { id: '2', name: 'Guided Ecology and Impact Opposites', maxPoints: 10 },
  { id: '3', name: 'Session Design — Fitness, Warm-Up, and Zone Structure', maxPoints: 10 },
  { id: '4', name: 'The Constraints Toolkit', maxPoints: 8 },
  { id: '5', name: 'Safety, Etiquette, and Course Conduct', maxPoints: 8 },
  { id: '6', name: 'Program-Specific Knowledge', maxPoints: 10 },
  { id: '7', name: 'Staff Operations and Professional Standards', maxPoints: 6 },
  { id: '8', name: 'Motivation, Psychology, and Parent Communication', maxPoints: 8 },
];

export const L2_ESSAYS = [
  {
    id: 'l2_essay_1',
    title: 'Constraints vs. Verbal Instruction',
    prompt: `A colleague trained in traditional instruction asks: "Why do you put a pool noodle in the way instead of just telling them to swing inside-out? Isn't it faster to just explain it?" In 200 words, explain why the ICC constraint-based approach produces better motor learning outcomes. Use at least one named principle from the curriculum.`,
    wordLimit: 200,
    gradingCriteria: [
      'Verbal instruction requires translation from declarative (knowing) to motor (doing) — a step that constraints bypass entirely',
      'At least one named principle: CLA, Guided Ecology, self-organization, ecological dynamics, or attractor dynamics',
      'The motor system responds to physical boundaries faster and more durably than to verbal cues alone',
      'The player discovers the solution rather than receiving it — discovery produces stronger encoding',
    ],
    passThreshold: 7,
  },
  {
    id: 'l2_essay_2',
    title: 'Coaching Across Developmental Levels',
    prompt: `You have a mixed group of 7-year-olds and 12-year-olds in the same Junior League session doing the Left-Right Discovery (Impact Opposites) activity. In 200 words, describe specifically how your instruction delivery, timing, language, and competitive framing differ for each age group during this same activity.`,
    wordLimit: 200,
    gradingCriteria: [
      'Different instruction length: 30-second maximum for ages 7 vs. longer with rationale for ages 12',
      'Different language: task-based ("make it curve that way") for ages 7 vs. named concepts (face angle, path, Primal Cue) for ages 12',
      'Different attention and rotation timing: shorter activity blocks for ages 7, longer sustained blocks for ages 12',
      'Different competitive framing: no scoring for ages 7 vs. Opposite Miss Challenge scoring for ages 12',
    ],
    passThreshold: 7,
  },
  {
    id: 'l2_essay_3',
    title: 'Handling a Parent Disagreement',
    prompt: `After a Junior League session, a parent says: "My son came home upset because another kid in the group is much better than him and keeps winning everything. You should either separate them or stop keeping score — losing is destroying his confidence." In 200 words, explain how you respond, what you would and would not change, and why competitive games with scoring serve the program's learning goals.`,
    wordLimit: 200,
    gradingCriteria: [
      "Acknowledge the parent's concern with genuine empathy — not dismissal",
      'Explain that scored games build competitive composure through graduated pressure (stress inoculation) — the learning rationale, not just "it\'s policy"',
      'Distinguish mastery climate (celebrating effort and improvement) from ego climate (ranking and outcome) — ICC runs mastery climate WITH competitive games',
      "Offer at least one specific adjustment that addresses the son's discouragement without eliminating competition (personal best tracking, ability-matched pairs, team formats, tiered challenges)",
    ],
    passThreshold: 7,
  },
];

export const L2_MC_POINTS = 1.0; // per question
export const L2_ESSAY_POINTS = 10; // per essay
export const L2_PASS_THRESHOLD = 80;
export const L2_TIME_LIMIT = 90 * 60; // 90 minutes in seconds
